server:
  port: 8080

spring:
  application:
    name: rarego
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_ACTIVE_PROFILES:dev}
  output:
    ansi:
      enabled: always