server:
  port: 8080

spring:
  application:
    name: rarego
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_ACTIVE_PROFILES:dev}
  output:
    ansi:
      enabled: always

toss:
  payments:
    secretKey: ${TOSS_PAYMENTS_SECRET_KEY}
    url: "https://api.tosspayments.com/v1/payments"

custom:
  global:
    internalBackUrl: ${INTERNAL_BACK_URL:http://localhost:8080}