server:
  port: 8080

spring:
  application:
    name: rarego
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_ACTIVE_PROFILES:dev}
  output:
    ansi:
      enabled: always
  batch:
    job:
      enabled: false

toss:
  payments:
    secretKey: ${TOSS_PAYMENTS_SECRET_KEY}
    url: "https://api.tosspayments.com/v1/payments"

aws:
  s3:
    bucket: rarego-auction-product-images
    expiration-minutes: 5
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  region: ap-northeast-2

jwt:
  secret: ${JWT_SECRET:dev-secret-key-have-to-change-abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz}
  access-token-expire-seconds: ${JWT_ACCESS_TOKEN_EXPIRE_SECONDS:3600}
  refresh-token-expire-seconds: ${JWT_ACCESS_TOKEN_EXPIRE_SECONDS:86400}

custom:
  global:
    internalBackUrl: ${INTERNAL_BACK_URL:http://localhost:8080}
  payment:
    systemMemberId: 2


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha