global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: rarego-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app:8080"]
